name: build-sphinx-to-gh-pages

on:
  push:
    branches:
      - master

jobs:
  build_sphinx_docs:
    name: Publish docs to Github Pages
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          persist-credentials: false

      - name: Install Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python3 -m pip install -U poetry -r dev-requirements.txt
          poetry install

      - name: Build Documentation
        run: make docs

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          branch: gh-pages
          folder: docs/build
